### ISSUE TITLE
AzureBlobFileProvider.GetFileInfo(string subpath) should not throw if the file does not exist

### ISSUE THREAD

**Issue by mssteele** [filipw/Strathweb.AspNetCore.AzureBlobFileProvider#13]
Hi @filipw

AzureBlobFileProvider.GetFileInfo(string subpath) should not throw if the file does not exist.
Instead it should return an IFileInfo object with property Exists == false.

I have fixed this locally - is it OK to send you pull request?

Thanks,
Michael

**Comment by filipw** [comment]
yes please!

**Comment by mssteele** [comment]
Thanks, there you go!

**Comment by n00bje** [comment]
@filipw Any chance you could publish this a bit early to NuGet? Currently Application Insights logs every 'failed' GetFileInfo call as a Azure blob dependency failure, even if you catch the Exception.

**Comment by filipw** [comment]
published https://www.nuget.org/packages/Strathweb.AspNetCore.AzureBlobFileProvider/0.4.0
